valid/basicapp/urls.py
from django.conf.urls import url,include
from basicapp import views

app_name = 'basicapp'

urlpatterns=[
    url(r'^register/',views.register,name='register'),
    url(r'^userlogin/',views.userlogin,name='login')
]

valid/valid/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basicapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'basicapp/',include('basicapp.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'logout/$',views.userlogout,name='logout'),
    url(r'special/',views.special,name='special'),
]

valid/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True)

    def __str__(self):
        return self.user.username

valid/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

valid/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm , UserProfileInfoForm

from django.contrib.auth import login,logout,authenticate
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'basicapp/index.html')

@login_required
def special(request):
    return HttpResponse("Welcome Bacche :P ")



@login_required
def userlogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered =True
        else:
            print('error in form')
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'basicapp/registration.html',{'registered':registered,
                                                        'user_form':user_form,
                                                        'profile_form':profile_form})
def userlogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else :
                return HttpResponse("Account is dea")
        else :
            return HttpResponse("invalid credentials")
    else:
        return render(request,'basicapp/login.html',{})

valid/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index'%}">HOME</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'basicapp:register'%}">Register</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout'%}">Pehli Fursat me nikal</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'special'%}">Kuch Khaaas!!</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'basicapp:login'%}"> Mujhe bhi to andar lo :( </a>
      </li>
      {% endif %}

    </ul>
  </div>
</nav>
      <div class="container">
        {% block bodyblock %}
        {% endblock %}
      </div>
  </body>
</html>

valid/templates/basicapp/index.html
<!DOCTYPE html>

{% extends "basicapp/base.html" %}
{% block bodyblock %}
<div class="jumbotron">
  <h1>!!!!!!! Level5 !!!!!!!</h1>
</div>
{% endblock %}

valid/templates/basicapp/login.html
{% extends "basicapp/base.html"%}
{% block bodyblock %}
<div class="jumbotron">
  <h1>Please Login :</h1>
  <form action="{% url 'basicapp:login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username :</label>
    <input type="text" name="username" placeholder="Username">

    <label for="password">Password :</label>
    <input type="password" name="password">
    <input type="submit" name="" value="Andar Aao ;)">
  </form>

</div>
{% endblock %}

valid/templates/basicapp/registration.html
<!DOCTYPE html>

{% extends "basicapp/base.html" %}
{% load staticfiles %}
{% block bodyblock %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank  You For Regestering</h1>
  {% else %}
  <h1>Register HERE!!</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}
    <input type="submit" name="" value="Register">
  </form>
  {% endif %}

</div>
{% endblock %}